import Navbar from "./Utils/Navbar";
import Home from "./Home/Home";
import Cart from "./Cart/Cart";
import Products from "./Products/Products";
import ProductDetails from "./Products/ProductDetials";
import Result from "./Result/Result";
import Loading from "./Utils/Loading";
import Footer from "./footer/Footer";
import Dashboard from "./user/Dashboard";
import Wishlist from "./Wishlist/Wishlist";
export { Navbar, Home, Cart, Products, Result, ProductDetails, Loading, Footer, Dashboard, Wishlist };
